name: Serverless Golang Starter

on:
  push:
    branches: [ main ]
env:
  AWS_REGION: us-east-1
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Go Packages
      run: sh build.sh

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install

    - name: serverless deploy
      uses: serverless/github-action@v2
      with:
        args: -c "serverless plugin install --name serverless-plugin-log-retention && serverless plugin install --name serverless-plugin-datadog@2.31.0 && serverless deploy --stage=int --verbose"
        entrypoint: /bin/sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.INT_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.INT_AWS_SECRET_ACCESS_KEY }}
